packages:
  - .
  - playground
catalogs:
  build:
    '@vitejs/plugin-vue': ^6.0.3
    tsdown: ^0.18.4
    unplugin-icons: ^22.5.0
    unplugin-lightningcss: ^0.4.4
    vite: ^7.3.0
  cli:
    bumpp: ^10.3.2
    pncat: ^0.7.7
    taze: ^19.9.2
  dev:
    happy-dom: ^20.0.11
  frontend:
    '@floating-ui/dom': ^1.7.4
  icons:
    '@iconify-json/lucide': ^1.2.82
    '@iconify-json/tabler': ^1.2.25
  lint:
    '@antfu/eslint-config': ^6.7.3
    '@unocss/eslint-plugin': ^66.5.12
    eslint: ^9.39.2
    eslint-plugin-format: ^1.1.0
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  prod:
    colord: ^2.9.3
  script:
    tsx: ^4.21.0
  style:
    '@unocss/reset': ^66.5.12
    unocss: ^66.5.12
  test:
    '@vue/test-utils': ^2.4.6
    vitest: ^4.0.16
  tsc:
    typescript: ^5.9.3
    vue-tsc: ^3.2.1
  types:
    '@types/node': ^25.0.3
  utils:
    '@vueuse/core': ^14.1.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
